baseURL = 'https://isabellamonica.com/'
languageCode = 'en-us'
title = 'Isabella Monica'

[environments.development]
baseURL = 'http://localhost:1313/'

[environments.production]
baseURL = 'https://isabellamonica.com/'
